###
GET http://localhost:8080/headers


###
GET http://localhost:8080/request-param-v2?username=moon&age=32

###
GET http://localhost:8080/request-param-v2?username=moon&age=32

###
GET http://localhost:8080/request-param-v3?username=moon&age=32

###
GET http://localhost:8080/request-param-v4?username=moon&age=32

###
GET http://localhost:8080/request-param-required?username=moon&age=32

###
GET http://localhost:8080/request-param-default

###
GET http://localhost:8080/request-param-map?username=moon&age=32

###
GET http://localhost:8080/model-attribute-v2?username=moon&age=32

###
POST http://localhost:8080/request-body-string-v1

hello

###
POST http://localhost:8080/request-body-string-v2

hello

###
POST http://localhost:8080/request-body-string-v3

hello

###
POST http://localhost:8080/request-body-string-v4

hello

###
POST http://localhost:8080/request-body-json-v1
Content-Type: application/json

{
  "username" : "msc",
  "age" : 1
}

###
POST http://localhost:8080/request-body-json-v2
Content-Type: application/json

{
  "username" : "msc",
  "age" : 1
}

###
POST http://localhost:8080/request-body-json-v3
Content-Type: application/json

{
  "username" : "msc",
  "age" : 1
}

###
POST http://localhost:8080/request-body-json-v4
Content-Type: application/json

{
  "username" : "msc",
  "age" : 1
}

###
POST http://localhost:8080/request-body-json-v5
Content-Type: application/json

{
  "username" : "msc",
  "age" : 1
}