###
GET http://localhost:8080/headers


###
GET http://localhost:8080/request-param-v2?username=moon&age=32

###
GET http://localhost:8080/request-param-v2?username=moon&age=32

###
GET http://localhost:8080/request-param-v3?username=moon&age=32

###
GET http://localhost:8080/request-param-v4?username=moon&age=32

###
GET http://localhost:8080/request-param-required?username=moon&age=32

###
GET http://localhost:8080/request-param-default

###
GET http://localhost:8080/request-param-map?username=moon&age=32

###
GET http://localhost:8080/model-attribute-v2?username=moon&age=32
